
import os


targetDir = "texts"
scriptPath = os.path.abspath(__file__)
scriptDir = os.path.dirname(scriptPath)


content = """
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
test texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest texttest text
"""

for i in range(10000):
    fileName = "test"+str(i)+".txt"
    targetFilePath = os.path.join(scriptDir,targetDir,fileName)
    with open(targetFilePath,'w') as file:
        file.write(content)
